### PR TITLE
readme

### PR DESCRIPTION
**Pull request by seantiz**
readme update with root.render method and div element included in steps

### CODE REVIEW

**Comment by jordan-pieces** [comment]
@seantiz i think this actually needs to be opened on the vanilla copilot repo : https://github.com/pieces-app/pieces-copilot-vanilla-typescript-example

**Comment by seantiz** [comment]
@jordan-pieces are you sure? the Vanilla TS example would be already pre-built. I thought we meant for these steps to be included in a readme where someone is building from scratch.

**Comment by jordan-pieces** [comment]
@seantiz i was just a bit confused because this PR has 10k changes, you can see that here in this screenshot:

Screenshot 2024-02-15 at 10 14 09 PM

**Comment by seantiz** [comment]
> @seantiz i was just a bit confused because this PR has 10k changes, you can see that here in this screenshot:
> 
> 
> 
> Screenshot 2024-02-15 at 10 14 09 PM
> 
> 

Woah, sorry, yeah. That comes down to my inexperience with PRs. This is the first PR I've made on GH ever. If you want to close this i can do it again properly in a new one.

**Pull request closed without merging**
